### ISSUE TITLE
Wrong number of slices in S2Si dict

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#174]
We have a new bug (thanks to @neuslopez for pointing it out). S2Si dicts are filled with zeros when a slice is empty for any charged sensor. However, **this is done just for those slices before the last one present in the input**; trailing zeros (empty slices at the end) are not included.

Solving this is non-trivial since the information of the actual number of slices is missing in the input (it is stored in the S2-PMT pmaps). My proposal is that, as suggested in #165, we store all empty slices as zeros in disk. This way, the problem is moved to the writing side, which has full information.

Note: we are just fine for now since we are not requiring slice info in the SiPMs.

**Comment by gonzaponte** [comment]
I will push a test demonstrating the problem shortly.

**Comment by gonzaponte** [comment]
Done in [gonzaponte/issue174](https://github.com/gonzaponte/IC/blob/issue174/invisible_cities/reco/pmaps_functions_test.py)

**Comment by jjgomezcadenas** [comment]
I think the problem should disappear in the branch maps-writer which is currently under PR. I did modify the S2Si structure so that it wrote all the samples from the beginning. Please check in the branch!

**Comment by jacg** [comment]
Please check that my [rephrasing of the test](https://github.com/jacg/IC/commit/66bcf116eecfaa58e78ab26be5d20b82c69e88c6) correctly conveys its intent.

**Comment by jacg** [comment]
> S2Si dicts are filled with zeros when a slice is empty for any charged sensor.

Where does this happen in the code? The comment suggests that it's here

    # Postprocessing: Turn lists to numpy arrays before returning and fill
    # empty slices with zeros
    for current_event in all_events.values():
        for current_peak in current_event.values():
            for ID, energy in current_peak.items():
                current_peak[ID] = np.array(energy)

But I'm failing to spot the filling with zeros.

>  However, **this is done just for those slices before the last one present in the input**

I can think of at least two interpretations of this, neither of which correlates with what I can see in the code, or the failure mode of the test.

Hints welcome.

**Comment by gonzaponte** [comment]
> Where does this happen in the code? The comment suggests that it's here

It has been already changed by JJ's last PR. Now zeros are directly stored in disk, so there is no need to manually fill them in the reading process.

The issue has been solved, but I am using this reference for including a new test so it does not happen again.

**Correction:**
The issue has not been solved. The test data file must be updated

**Comment by jacg** [comment]
> The issue has been solved

That is indeed what the conversation suggested. But the test is still failing! I find tests far more convincing that opinions. I guess this means that you need to update the data file that the fixture uses? By re-generating it, using the new writer?

**Comment by jacg** [comment]
If the problem is indeed solved, and the padding does come from the file, then the misleading comment shown above should be fixed.

**Comment by gonzaponte** [comment]
> But the test is still failing! 

Indeed. This should have been made in the PR. If you want me to fix it, please push this to my branch (con mucha fuerza, I have rebased onto master). We do not have data yet, but should be ready today.

**Comment by jacg** [comment]
> please push this to my branch (con mucha fuerza)

In general, I'd rather not.

In this case, as it's not a PR (with reviewer modification enabled) I couldn't even if I wanted to.

Anything wrong with fetching it from my fork? Then you can decide for yourself what changes in yours, rather than having it imposed on you from outside.

**Comment by gonzaponte** [comment]
Right. I will do that.

**Comment by gonzaponte** [comment]
I have updated the data file for testing and the problem is still there. It seems we are not ***always*** matching slices in PMTs and SiPMs. For example for event 36, peak 0 in the test file we have (read directly from disk):
````
# S2-PMT
# evt peak time ene
(36, 0, 589082.5, 67.44696044921875)
(36, 0, 590112.5, 186.23150634765625)
(36, 0, 591112.5, 339.8017578125)
(36, 0, 592112.5, 540.70458984375)
(36, 0, 593112.5, 811.3622436523438)
(36, 0, 594112.5, 904.944580078125)
(36, 0, 595112.5, 896.51123046875)
(36, 0, 596112.5, 714.30078125)
(36, 0, 597112.5, 424.61480712890625)
(36, 0, 598112.5, 201.59349060058594)
(36, 0, 599120.0, 86.34136199951172)
(36, 0, 599981.25, 21.835777282714844)

# S2-SiPM, SiPM #1313
# evt peak nsipm ene
(36, 0, 1313, 9.7039155960083)
(36, 0, 1313, 0.0)
(36, 0, 1313, 0.0)
(36, 0, 1313, 0.0)
(36, 0, 1313, 10.723725318908691)
(36, 0, 1313, 17.73491668701172)
(36, 0, 1313, 0.0)
(36, 0, 1313, 0.0)
(36, 0, 1313, 0.0)
(36, 0, 1313, 0.0)
(36, 0, 1313, 0.0)
# similar stuff for SiPMs 1306, 1307, 1314, 1315
````

And for event 37, peak 0:
````
# S2-PMT
# evt peak time ene
(37, 0, 337182.5, 127.9377670288086)
(37, 0, 338187.5, 509.8338317871094)
(37, 0, 339187.5, 1042.1185302734375)
(37, 0, 340187.5, 1552.5150146484375)
(37, 0, 341187.5, 1570.56884765625)
(37, 0, 342187.5, 1005.8583374023438)
(37, 0, 343187.5, 470.96600341796875)
(37, 0, 344220.625, 123.60220336914062)
(37, 0, 345060.0, 19.41663360595703)

# S2-SiPM, SiPM #421
# evt peak nsipm ene
(37, 0, 421, 3.9372692108154297)
(37, 0, 421, 17.966449737548828)
(37, 0, 421, 20.95527458190918)
(37, 0, 421, 25.95698356628418)
(37, 0, 421, 25.77399444580078)
(37, 0, 421, 11.0738525390625)
(37, 0, 421, 0.0)
(37, 0, 421, 0.0)
(37, 0, 421, 0.0)
# similar stuff for SiPMs 422, 413, 414
````

In event 36, S2-PMT contains 12 slices, while S2-SiPM contains 11 slices (in all SiPMs). On the other hand, event 37 has 9 slices both in S2-PMT and S2-SiPM.

I have gone through the chain that produces the S2Si pmaps and it is not clear to me where is the error introduced, but I suspect it is somewhere in the sipm-related functions of peak_functions.py (sipm_s2*). Because debugging it involves Irene, I don't want to dig too much until @jjgomezcadenas takes a look to this, as it may be obvious to him. So, do you have any idea of what's going on?

**Comment by jjgomezcadenas** [comment]
Thanks @gonzaponte great work!
I don't think debugging involves Irene, which uses functions mostly from peak_functions and pmaps_functions. I suspect the problem comes from rounding error when rebbinning in S2, but I have no idea where it is. Will be very grateful if you and or @jmbenlloch can take a look. Right now I am in Canfranc, trying to make sense of initial data, have very little time for digging into code.

**Comment by gonzaponte** [comment]
Ok then.

> I don't think debugging involves Irene, ...

It does not involve Irene as long as you extract the event that fails from the data so you have a failing example to study what is going on, so I will do that.

**Comment by gonzaponte** [comment]
The problem comes when t[i+1] - t[i] < 1 mus. For some reason, the last two elements of the S2-PMT time array are within 1 mus:
```
array([ 589082.5 ,  590112.5 ,  591112.5 ,  592112.5 ,  593112.5 ,
        594112.5 ,  595112.5 ,  596112.5 ,  597112.5 ,  598112.5 ,
        599120.  ,  599981.25])
```
This causes the function `index_from_s2` to return the indices 589 and 600, and the difference is then 11 rather than the original 12 slices. This can be easily fixed by ***rounding*** the time array instead of flooring it, but the question is: should we allow this dt < 1 mus?

**Comment by jjgomezcadenas** [comment]
Yes, I believe that 1 mus is a very acceptable time resolution

**Comment by gonzaponte** [comment]
I think there is a more profound problem here...

Imagine the case attached. Solid lines represent integer values of time in mus, while dashed lines represent time slices created by rebinning the waveform. They don't match because we define the beginning of the slice to be the first sample above threshold.

Everything in the drawing correspond to the same peak, as the beginning of one piece is less than 40 samples away to the end of the previous one. The value of `t` corresponding to each slice will be something like ~1.1, ~2.2 and ~2.9 mus (mean of t in each time slice). If we take the integer part (as we do now) we will have 1, 2 and 2, which is incorrect for our purpose. If you perform the rounding, as I suggested earlier, you can fix this case, but it is possible to find another one where it does not work.

On top of this, we are not exactly matching tracking plane (integer values of mus) and energy plane (discrete, but not necessarily integer values of mus) unless the signal starts at an integer number of mus. I don't know if this is a concern for you, @jjgomezcadenas, but it makes me uncomfortable. I think we already talked about that in November, but I don't remember the conclusion.

To conclude, I think the only solution to this is to exactly match the slices for the energy and the tracking plane, but this will be a very serious change in the code affecting the PMT ZS and the finding of S12.

![drawing](https://cloud.githubusercontent.com/assets/8233521/24115105/9a7ab15a-0da2-11e7-9e55-d378ae6e58da.png)

**Comment by jjgomezcadenas** [comment]
I agree the current solution is less than perfect, but how often we run into this, and how bad it is? My feeling is that it is irrelevant, since everything stays within ranges of 1 bus, which is a small quantity compared with our resolution (due to diffusion and grid).

Fixing it, as you well realise would be a major effort (and one has to watch out performance). Of course, if you want to give it a try I have no problems, but my feeling is that it is not affecting us at all.

**Comment by gonzaponte** [comment]
> I agree the current solution is less than perfect

The point is that this solution solves the current bug, but introduces another one.

> but how often we run into this

Difficult to quantify, but let's say it is of the order of 1%.

> and how bad it is?

It is ***not too bad*** in the sense that we are working with that right now and it is not critical (partially because I am not using time slices in the SiPMs at all).

I may have found another solution, but it is kinda nasty. Instead of picking the minimum and maximum of time values to compute the SiPM slices, simply take the minimum value and add the number of slices provided by the cathode.

Are you happy with this? It is still a minor fix and much less prone to errors.

**Comment by jjgomezcadenas** [comment]
>I may have found another solution, but it is kinda nasty. Instead of picking the minimum and maximum of time values to compute the SiPM slices, simply take the minimum value and add the number of slices provided by the cathode.

Actually, I think this is a brilliant solution.


>Are you happy with this? It is still a minor fix and much less prone to errors.

Absolutely!

**Comment by gonzaponte** [comment]
I'll push that, then.

**Comment by gonzaponte** [comment]
I have pushed the fix and updated test file. All tests passed. I will open a PR and if everybody is happy, I can squash it to a single commit and then you can merge it into master.

**Comment by jacg** [comment]
Can this be closed?

**Comment by jjgomezcadenas** [comment]
yes, tis is done, I am closing it.
